-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE BPO_WORKFORCE;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.SITES (
  SITE_ID VARCHAR(20) NOT NULL, SITE_NAME VARCHAR(200), CITY VARCHAR(50), COUNTRY VARCHAR(30), SERVICE_TYPE VARCHAR(50), SEATS INT, UTILIZATION_PCT FLOAT, CLIENT_COUNT INT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.AGENTS (
  AGENT_ID VARCHAR(20) NOT NULL, SITE_ID VARCHAR(20), AGENT_NAME VARCHAR(100), SKILL_GROUP VARCHAR(50), TENURE_MONTHS INT, PERFORMANCE_SCORE FLOAT, STATUS VARCHAR(20), HIRE_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.INTERACTIONS (
  INTERACTION_ID VARCHAR(30) NOT NULL, AGENT_ID VARCHAR(20), CLIENT_ID VARCHAR(20), INTERACTION_DATE TIMESTAMP, CHANNEL VARCHAR(20), HANDLE_TIME_SECS INT, WAIT_TIME_SECS INT, DISPOSITION VARCHAR(30), CSAT_SCORE INT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.CLIENTS (
  CLIENT_ID VARCHAR(20) NOT NULL, CLIENT_NAME VARCHAR(200), INDUSTRY VARCHAR(50), CONTRACT_VALUE FLOAT, SLA_TARGET FLOAT, START_DATE DATE, STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
