-- ============================================================================
-- 04_DYNAMIC_TABLES.SQL - Curated analytics layer with real aggregations
-- ============================================================================
USE DATABASE BPO_WORKFORCE;
USE SCHEMA CURATED;

CREATE OR REPLACE DYNAMIC TABLE CURATED.SITE_SUMMARY
  TARGET_LAG = '5 minutes'
  WAREHOUSE = BPO_WORKFORCE_WH
AS
SELECT
  a.SITE_ID,
  COUNT(DISTINCT t.TXN_ID) AS TOTAL_EVENTS,
  ROUND(SUM(t.AMOUNT), 0) AS TOTAL_VALUE,
  ROUND(AVG(t.AMOUNT), 0) AS AVG_VALUE,
  ROUND(SUM(CASE WHEN t.STATUS IN ('COMPLETED','DELIVERED','PASSED') THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) * 100, 1) AS SUCCESS_RATE,
  MIN(t.TXN_DATE) AS FIRST_EVENT,
  MAX(t.TXN_DATE) AS LAST_EVENT,
  COUNT(DISTINCT CASE WHEN t.TXN_DATE >= DATEADD('day', -30, CURRENT_DATE()) THEN t.TXN_ID END) AS EVENTS_LAST_30D
FROM RAW.SITES a
LEFT JOIN RAW.AGENTS t ON a.SITE_ID = t.SITE_ID
GROUP BY 1;

CREATE OR REPLACE DYNAMIC TABLE CURATED.WEEKLY_TRENDS
  TARGET_LAG = '5 minutes'
  WAREHOUSE = BPO_WORKFORCE_WH
AS
SELECT
  DATE_TRUNC('week', TXN_DATE) AS WEEK_START,
  CATEGORY,
  COUNT(*) AS EVENT_COUNT,
  ROUND(SUM(AMOUNT) / 1000000, 2) AS AMOUNT_MILLIONS,
  ROUND(AVG(AMOUNT), 0) AS AVG_AMOUNT,
  COUNT(DISTINCT SITE_ID) AS ACTIVE_ENTITIES,
  ROUND(SUM(CASE WHEN STATUS IN ('COMPLETED','DELIVERED','PASSED') THEN AMOUNT ELSE 0 END) / NULLIF(SUM(AMOUNT), 0) * 100, 1) AS SUCCESS_RATE
FROM RAW.AGENTS
GROUP BY 1, 2;

CREATE OR REPLACE DYNAMIC TABLE CURATED.ENTITY_RANKING
  TARGET_LAG = '5 minutes'
  WAREHOUSE = BPO_WORKFORCE_WH
AS
WITH ranked AS (
  SELECT
    SITE_ID,
    SUM(TOTAL_VALUE) AS TOTAL_VALUE,
    AVG(SUCCESS_RATE) AS AVG_SUCCESS,
    SUM(EVENTS_LAST_30D) AS RECENT_ACTIVITY
  FROM CURATED.SITE_SUMMARY
  GROUP BY 1
)
SELECT *,
  RANK() OVER (ORDER BY TOTAL_VALUE DESC) AS VALUE_RANK,
  RANK() OVER (ORDER BY AVG_SUCCESS DESC) AS QUALITY_RANK,
  NTILE(4) OVER (ORDER BY TOTAL_VALUE DESC) AS QUARTILE
FROM ranked;