-- Generated from generator/demo_specs/aws-philippines-bpo-workforce.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-bpo-workforce
-- This is the schema that is actually deployed for PH_BPO_WORKFORCE.

-- Alerts fire on the top tail of Attrition Rate
-- (higher is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.91) WITHIN GROUP (ORDER BY KPI_ATTRITION_RATE) AS T
  FROM RAW.ATTENDANCE_LOGS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_ATTRITION_RATE >= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_ATTRITION_RATE), 2) AS AVG_ATTRITION_RATE,
  ROUND(AVG(f.KPI_TRAINING_COMPLETION), 2) AS AVG_TRAINING_COMPLETION,
  ROUND(AVG(f.KPI_AVG_TENURE), 2) AS AVG_TENURE,
  ROUND(AVG(f.KPI_PROMOTION_RATE), 2) AS AVG_PROMOTION_RATE,
  ROUND(AVG(f.KPI_ENGAGEMENT_SCORE), 2) AS AVG_ENGAGEMENT_SCORE
FROM RAW.ATTENDANCE_LOGS f
JOIN RAW.LABOR_MARKET e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_ATTRITION_RATE), 2) AS AVG_ATTRITION_RATE,
  ROUND(AVG(f.KPI_TRAINING_COMPLETION), 2) AS AVG_TRAINING_COMPLETION,
  ROUND(AVG(f.KPI_AVG_TENURE), 2) AS AVG_TENURE,
  ROUND(AVG(f.KPI_PROMOTION_RATE), 2) AS AVG_PROMOTION_RATE,
  ROUND(AVG(f.KPI_ENGAGEMENT_SCORE), 2) AS AVG_ENGAGEMENT_SCORE
FROM RAW.ATTENDANCE_LOGS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_ATTRITION_RATE) AS KPI_ATTRITION_RATE, AVG(KPI_TRAINING_COMPLETION) AS KPI_TRAINING_COMPLETION, AVG(KPI_AVG_TENURE) AS KPI_AVG_TENURE, AVG(KPI_PROMOTION_RATE) AS KPI_PROMOTION_RATE, AVG(KPI_ENGAGEMENT_SCORE) AS KPI_ENGAGEMENT_SCORE FROM RAW.ATTENDANCE_LOGS),
     en AS (SELECT SUM(KPI_TOTAL_HEADCOUNT) AS KPI_TOTAL_HEADCOUNT, SUM(KPI_OPEN_POSITIONS) AS KPI_OPEN_POSITIONS FROM RAW.LABOR_MARKET)
  SELECT 1 AS SORT_ORDER, 'Total Headcount' AS TITLE, KPI_TOTAL_HEADCOUNT AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_TOTAL_HEADCOUNT)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Attrition Rate' AS TITLE, KPI_ATTRITION_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ATTRITION_RATE), 1) AS DECIMAL(38,1))) || '%/mo' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Training Completion' AS TITLE, KPI_TRAINING_COMPLETION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_TRAINING_COMPLETION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Open Positions' AS TITLE, KPI_OPEN_POSITIONS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_OPEN_POSITIONS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Avg Tenure' AS TITLE, KPI_AVG_TENURE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_TENURE), 1) AS DECIMAL(38,1))) || ' ' || 'yrs' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Promotion Rate' AS TITLE, KPI_PROMOTION_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PROMOTION_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Engagement Score' AS TITLE, KPI_ENGAGEMENT_SCORE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ENGAGEMENT_SCORE), 1) AS DECIMAL(38,1))) || '/5' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
