-- ============================================================================
-- 99_RESET.SQL — Reset BPO Workforce Analytics & Attrition Prediction to clean demo state
-- ============================================================================
USE DATABASE BPO_WORKFORCE;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_RETRAIN_ATTRITION_MODEL SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SCORE_AGENTS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_NOTIFY_HR SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.SITE_ATTRITION_SUMMARY REFRESH;
ALTER DYNAMIC TABLE CURATED.AGENT_RISK_PROFILE REFRESH;
ALTER DYNAMIC TABLE CURATED.ATTRITION_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.TRAINING_EFFECTIVENESS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM BPO_WORKFORCE.RAW.AGENTS → 28000
-- SELECT COUNT(*) FROM BPO_WORKFORCE.RAW.ATTENDANCE_LOGS → 850000
-- SELECT COUNT(DISTINCT SITE_ID) FROM BPO_WORKFORCE.CURATED.SITE_ATTRITION_SUMMARY WHERE ATTRITION_STATUS = 'CRITICAL' → 3

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_NOTIFY_HR RESUME;
ALTER TASK IF EXISTS APP.TASK_SCORE_AGENTS RESUME;
ALTER TASK IF EXISTS APP.TASK_RETRAIN_ATTRITION_MODEL RESUME;
